name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Build job
  jekyll-build:
    name: Build Gem
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false
      - name: Bundle install
        run: bundle install
      - name: Build with Jekyll
        run: bundle exec jekyll build

  validate:
    name: Validate HTML
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.3"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v3
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
      - name: Bundle install
        run: bundle install
      - name: Build Site
        run: bundle exec jekyll build
      - name: Test with Nu Validator
        uses: Cyb3r-Jak3/html5validator-action@2a593a9f2c10593cbac84791a6fc4c47e9a106c8
        with:
          config: fixtures/html5validator-config.yml
      - name: Test with html-proofer
        run:
          bundle exec htmlproofer _site --ignore-urls
          "/github.com/,/web.archive.org/,/ondemand.talapas.uoregon.edu/,/uoracs.github.io/,/filezilla-project.org/,/wiki.talapas.uoregon.edu/,/slurm.schedmd.com/"
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
